/*
 * dx12_shader.h / dx12_shader.cpp
 * COMPONENT: 1 (Backend Core)
 * PURPOSE: Shader loading, PSO creation, embedded CSO management
 *
 * CODE INTEGRATION POINTS:
 *   - Called by: dx12_graph.cpp (loads shaders for each op)
 *   - Called by: dx12_gemm.cpp (loads GEMM shaders)
 *   - Uses:      dx12_descriptor.cpp (root signatures, PSO cache)
 *   - Uses:      dx12_shader_registry (auto-generated from .cso files)
 *   - Provides:  Shader dispatch setup to graph execution
 */

#ifndef DX12_SHADER_H
#define DX12_SHADER_H

#include "dx12_device.h"
#include "dx12_descriptor.h"
#include "dx12_command.h"
#include <unordered_map>
#include <string>
#include <mutex>

// ═══════════════════════════════════════════════════════════════════════════════
// Shader Registry Entry (auto-generated from compiled .cso files)
// ═══════════════════════════════════════════════════════════════════════════════

struct dx12_shader_entry {
    const char*     name;           // e.g., "mul_mat_f16_f16"
    const uint8_t*  cso_data;       // Embedded .cso byte array
    size_t          cso_size;       // Size in bytes
    uint32_t        thread_group_x; // Default threadgroup dimensions
    uint32_t        thread_group_y;
    uint32_t        thread_group_z;
};

// Auto-generated by compile_shaders.ps1
extern const dx12_shader_entry DX12_SHADER_REGISTRY[];
extern const size_t DX12_SHADER_COUNT;

// ═══════════════════════════════════════════════════════════════════════════════
// Shader Database
// ═══════════════════════════════════════════════════════════════════════════════

struct dx12_shader_db {
    std::unordered_map<std::string, const dx12_shader_entry*> entries;
    std::mutex mutex;
    bool initialized = false;

    void init();
    const dx12_shader_entry* find(const char* name);
    const dx12_shader_entry* find(const char* name, dx12_device_caps* caps);
};

// ═══════════════════════════════════════════════════════════════════════════════
// Shader Dispatch Helper
// ═══════════════════════════════════════════════════════════════════════════════

struct dx12_shader_dispatch {
    const char*                 shader_name;
    dx12_root_signature_type    sig_type;
    uint32_t                    thread_group_x;
    uint32_t                    thread_group_y;
    uint32_t                    thread_group_z;
};

/**
 * dx12_shader_dispatch — Load shader, create PSO, bind, and dispatch
 *
 * This is the main entry point for executing a compute shader:
 * 1. Looks up CSO from embedded registry
 * 2. Creates/caches PSO
 * 3. Binds root signature
 * 4. Binds buffers and constants
 * 5. Dispatches compute
 */
bool dx12_shader_dispatch(dx12_device* dev,
                          dx12_command_list* cmd,
                          const dx12_shader_dispatch& dispatch,
                          const void* constants, size_t constants_size,
                          dx12_buffer** srvs, uint32_t num_srvs,
                          dx12_buffer* uav);

/**
 * dx12_shader_dispatch_simple — Convenience for simple elementwise ops
 *
 * 2 SRV inputs + 1 UAV output + constants
 */
bool dx12_shader_dispatch_simple(dx12_device* dev,
                                 dx12_command_list* cmd,
                                 const char* shader_name,
                                 const void* constants, size_t constants_size,
                                 dx12_buffer* srv_a,
                                 dx12_buffer* srv_b,
                                 dx12_buffer* uav,
                                 uint32_t elements);

/**
 * dx12_shader_dispatch_gemm — Convenience for GEMM ops
 *
 * 2 SRV matrices + 1 UAV result + GEMM params
 */
bool dx12_shader_dispatch_gemm(dx12_device* dev,
                               dx12_command_list* cmd,
                               const char* shader_name,
                               dx12_buffer* matrix_a,
                               dx12_buffer* matrix_b,
                               dx12_buffer* result,
                               uint32_t M, uint32_t N, uint32_t K,
                               bool transposed_b);

/**
 * dx12_get_shader_entry — Look up a shader by name
 */
const dx12_shader_entry* dx12_get_shader_entry(const char* name);

/**
 * dx12_shader_db_init — Initialize global shader database
 */
void dx12_shader_db_init();

#endif // DX12_SHADER_H
